# General
title: Design Cases
email: eliezerpujols@outlook.com
url: https://eliezerpujols.github.io
baseurl: ""
permalink: "/cases/:title/"
collections:
   showcases:

# Build Settings
exclude:
   - README.md
   - prepros-6.config