# General
title: Design Cases
email: eliezerpujols@outlook.com
baseurl: /design-cases
permalink: /cases/:title

# Collections
collections:
   modals: 

# Build Settings
exclude:
   - README.md
   - prepros-6.config
