# General
title: Design Cases
email: eliezerpujols@outlook.com
baseurl: "design-cases"
permalink: "/cases/:title/"
collections:
   showcases:

# Build Settings
exclude:
   - README.md
   - prepros-6.config